# pyproject.toml (fixed)

[project]
name = "whatsapp-mcp-server"
version = "0.1.0"
description = "WhatsApp MCP Server using FastMCP"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "fastapi",
    "fastmcp",  
    "requests>=2.32.3",
]
